name: ci_cd

permissions:
  contents: write
  packages: write

on:
  # CI triggers on pushes and pull requests to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # CD triggers on creation of a new release
  release:
    types: [created]

jobs:
  # Continuous Integration: Build and Test
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build DummyDB
        run: make

      - name: Run Tests
        run: make test

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t dummydb:test .

      - name: Docker Smoke Test
        run: docker run --rm dummydb:test

  # Continuous Deployment: Release
  deploy:
    runs-on: ubuntu-latest

    needs: build-and-test

    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build DummyDB Release Binary
        run: |
          make clean
          make release
          mv build/main build/dummydb

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/dummydb
            LICENSE

      - name: Lowercase Image Name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/dummydb:latest
            ghcr.io/${{ env.REPO_LOWER }}/dummydb:${{ github.ref_name }}